Tweak packaging headers
dylan-lang/dylan-emacs-support pull request #57
Opened 2021-03-14 09:00 UTC by lassik

Final fixes to copyright, authorship, and version headers for the MELPA package split.

I trawled the Git logs to get the copyright information hopefully comprehensive.

2021-03-14 18:24 UTC, lassik commented
@cgay @housel OK? Now we should have everything we need for the MELPA package split.

2021-03-14 19:52 UTC, pedro-w commented
Not quite ready, README.md refers to `(dime-setup '(dime-dylan dime-repl dime-compiler-notes-tree))` and this is no longer correct.

2021-03-14 19:58 UTC, lassik commented
@pedro-w Thanks for checking the work! I updated the dime contrib names. `dime-dylan.el` no longer exists - it has been merged into `dime.el`. Should `dime-browse` be a contrib?

2021-03-15 03:09 UTC, cgay requested changes

2021-03-15 03:09 UTC, cgay commented on dylan-lid.el
> +;;; dylan-lid.el --- Dylan editing modes -*- lexical-binding: t -*-
This seems not quite as accurate as the line it's replacing. What's the motivation?

2021-03-15 03:09 UTC, cgay commented on dylan-opt.el
> +;;; dylan-opt.el --- Dylan editing modes -*- lexical-binding: t -*-
Same question here.

2021-03-15 03:09 UTC, cgay commented on dylan.el
> +;;; dylan.el --- Dylan editing modes -*- lexical-binding: t -*-
and here. The original wasn't ideal either, but why not "Dylan major mode" or similar?

2021-03-15 06:32 UTC, lassik commented on dylan.el
> +;;; dylan.el --- Dylan editing modes -*- lexical-binding: t -*-
If the MELPA package name is `dylan`, it gets the package description from the `dylan.el` file description. Since the package includes all three editing modes (dylan-mode, dylan-opt-mode, dylan-lid-mode) calling it "Dylan editing modes" is more accurate than just one major mode. I changed it to "editing modes" to better distinguish it from the Dime package which is an "interaction mode".

We could separate the package description from the file description, but that necessitates an extra `-pkg.el`. MELPA recommends against that. The file description from `dylan-opt.el` and `dylan-lid.el` is not used for anything in particular, so I just harmonized it with the `dylan.el` description.

2021-03-15 06:34 UTC, lassik commented on dylan.el
> +;;; dylan.el --- Dylan editing modes -*- lexical-binding: t -*-
The first line of `dylan.el` (and `dime.el`) will go into the Description column on the [MELPA homepage](https://melpa.org/#/). It also goes into the `M-x list-packages` listing. There's not much room to write anything extensive and have it all show up on the screen, maybe 50-100 characters.

2021-03-15 16:22 UTC, cgay approved these changes

2021-03-17 04:03 UTC, housel approved these changes

2021-03-17 04:03 UTC, housel commented on README.rst
> +This repo contains two Emacs packages installable from `MELPA
"repository"

2021-03-17 14:05 UTC, merged